/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c74746b7-164e-4edb-91c1-1e946f984fbb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BkpCSFFGV",
    "aws_user_pools_web_client_id": "o6ein8d4epek0a0frekbuhgbc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "basearchivof25d0-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
